### ISSUE TITLE
Columns within households and recipients table must be added for API to function

### ISSUE THREAD

**Issue by LoganTilley** [Lambda-School-Labs/family-promise-service-tracker-ds-a#23]
**Note:** There is a near copy of this issue on the BE, as this issue directly involves both repositories. 

## recipients

- has_disability: bool
- has_valid_ssi: bool
- has_valid_medicare_card: bool

## households

- is_unstable: bool

Details for each of these can be found within the Trello board under **KnownDefects.md DS**. These must be added for the DS API eligibility endpoint to function.

## Implementation

It had been mentioned by our stakeholder in our last stakeholder meeting that `knex` migrations are pretty straightforward, so even though we're pythonistas, if you're up for some back end work, learning how to modify the database within the BE repository could prove to speed up the development process. Perhaps the web team could provide some assistance getting started with it.

**Comment by santorap** [comment]
Resolved as part of [similar issue on the backend](https://github.com/Lambda-School-Labs/family-promise-service-tracker-be-a/issues/114).
